### PR TITLE
Separated benefits sections/topics into pages

### LINKED ISSUE #11: Break Benefits sections out into separate pages
- [ ] Update side nav
- [ ] Add resource links

### PR DESCRIPTION
**Pull request by bnaolu**
Closes #11 
- folder created for individual pages
- added site.baseurl variable to the side-navigation include

### CODE REVIEW

**Comment by bnaolu** [comment]
Great catch, @pglevy! Pages weren't linking correctly because of the missing site.baseurl in the side navigation include! 😆

**Review by pglevy — CHANGES_REQUESTED** [review]
Looking good overall, but two requested changes:

1. Let's includes the section in the permalink so the url structure follows the site structure (so, /benefits/focus-on-the-important-stuff/)
2. We talked about moving the nav content out into a separate data (yml) file. The issue with this approach is that if/when we have to make changes to the navigation, we'll have to make those changes on every page (instead of just one place that gets included into the template).

**Comment by bnaolu** [comment]
> Looking good overall, but two requested changes:
> 
> 1. Let's includes the section in the permalink so the url structure follows the site structure (so, /benefits/focus-on-the-important-stuff/)
> 2. We talked about moving the nav content out into a separate data (yml) file. The issue with this approach is that if/when we have to make changes to the navigation, we'll have to make those changes on every page (instead of just one place that gets included into the template).

1. Gotcha, I'll make those changes.
2. Okay, so add a .yml file for the side nav to avoid making constant changes to every page if/when changes are made. Got it!

**Comment by pglevy** [comment]
Interesting approach on the side nav! I hadn't seen the parameters being passed into the includes before. Going to make a few minor tweaks and merge.

**Review by pglevy — APPROVED** [review]

**Pull request merged**
